const ADD_POST = "profileReducer/ADD-POST";
const SET_USER_STATUS = "profileReducer/SET_USER_STATUS";
const SET_USER_PROFILE = "profileReducer/SET_USER_PROFILE";
const ADD_MESSAGE = "dialogsReducer/ADD_MESSAGE";
const FOLLOW = "usersReducer/FOLLOW";
const UNFOLLOW = "usersReducer/UNFOLLOW";
const SET_USERS = "usersReducer/SET_USERS";
const SET_CURRENT_PAGE = "usersReducer/SET_CURRENT_PAGE";
const SET_COUNT_PAGES = "usersReducer/SET_COUNT_PAGES";
const SET_TOGGLE_LOADING = "usersReducer/SET_TOGGLE_LOADING";
const SET_FOLLOWING_STATUS = "usersReducer/SET_FOLLOWING_STATUS";
const SET_AUTH_ME_DATA = "authReducer/SET_AUTH_ME_DATA";
const INITIALIZED_SUCCESS = "app/INITIALIZED_SUCCESS";
const SAVE_PHOTO_SUCCESS = "profile/SAVE_PHOTO_SUCCESS";
const UPLOAD_PHOTO_STATUS = "profile/UPLOAD_PHOTO_STATUS";

export {
  ADD_POST,
  SET_USER_STATUS,
  SET_USER_PROFILE,
  ADD_MESSAGE,
  FOLLOW,
  UNFOLLOW,
  SET_USERS,
  SET_CURRENT_PAGE,
  SET_COUNT_PAGES,
  SET_TOGGLE_LOADING,
  SET_FOLLOWING_STATUS,
  SET_AUTH_ME_DATA,
  INITIALIZED_SUCCESS,
  SAVE_PHOTO_SUCCESS,
  UPLOAD_PHOTO_STATUS,
};
